import { ProductType } from '../types/ProductType';

export const productsDB: ProductType[] = [
  {
    id: 'p001',
    name: 'Entrada 1',
    description: 'Description',
    price: 1,
    active: true,
    categoryId: 'ca01',
    additionals: [
      {
        id: 'add001',
        name: 'Additional 1',
        price: 2,
      },
      {
        id: 'add002',
        name: 'Additional 2',
        price: 1.5,
      },
    ],
    requiredOption: [
      {
        id: 'req001',
        name: 'Required 1',
        price: 0,
      },
      {
        id: 'req002',
        name: 'Required 2',
        price: 1.2,
      },
    ],
  },
  {
    id: 'p002',
    name: 'Prato 1',
    description: 'Descrição',
    price: 2,
    active: true,
    categoryId: 'ca02',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p003',
    name: 'Petisco 1',
    description: 'Descrição',
    price: 3,
    active: true,
    categoryId: 'ca03',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p004',
    name: 'Snack 1',
    description: 'Descrição',
    price: 4,
    active: true,
    categoryId: 'ca04',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p005',
    name: 'Sobremesa 1',
    description: 'Descrição',
    price: 5,
    active: true,
    categoryId: 'ca05',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p006',
    name: 'Refrigerante 1',
    description: 'Descrição',
    price: 6,
    active: false,
    categoryId: 'ca06',
    additionals: [],
    requiredOption: [],
    imageUrl: './dist/assets/images/refri.png',
  },
  {
    id: 'p007',
    name: 'Suco 1',
    description: 'Descrição',
    price: 7,
    active: true,
    categoryId: 'ca07',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p008',
    name: 'Cerveja 1',
    description: 'Descrição',
    price: 8,
    active: true,
    categoryId: 'ca08',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p009',
    name: 'Bebida 1',
    description: 'Descrição',
    price: 9,
    active: true,
    categoryId: 'ca09',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p010',
    name: 'Drink 1',
    description: 'Descrição',
    price: 10,
    active: true,
    categoryId: 'ca10',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p011',
    name: 'Entrada 2',
    description: 'Descrição',
    price: 11,
    active: true,
    categoryId: 'ca01',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p012',
    name: 'Prato 2',
    description: 'Descrição',
    price: 12,
    active: true,
    categoryId: 'ca02',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p013',
    name: 'Petisco 2',
    description: 'Descrição',
    price: 13,
    active: true,
    categoryId: 'ca03',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p014',
    name: 'Snack 2',
    description: 'Descrição',
    price: 14,
    active: true,
    categoryId: 'ca04',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p015',
    name: 'Sobremesa 2',
    description: 'Descrição',
    price: 15,
    active: true,
    categoryId: 'ca05',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p016',
    name: 'Refrigerante 2',
    description: 'Descrição',
    price: 16,
    active: true,
    categoryId: 'ca06',
    additionals: [],
    requiredOption: [],
    imageUrl: './dist/assets/images/refri.png',
  },
  {
    id: 'p017',
    name: 'Suco 2',
    description: 'Descrição',
    price: 17,
    active: true,
    categoryId: 'ca07',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p018',
    name: 'Cerveja 2',
    description: 'Descrição',
    price: 18,
    active: true,
    categoryId: 'ca08',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p019',
    name: 'Bebida 2',
    description: 'Descrição',
    price: 19,
    active: true,
    categoryId: 'ca09',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p020',
    name: 'Drink 2',
    description: 'Descrição',
    price: 20,
    active: true,
    categoryId: 'ca10',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p021',
    name: 'Entrada 3',
    description: 'Descrição',
    price: 21,
    active: true,
    categoryId: 'ca01',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p022',
    name: 'Prato 3',
    description: 'Descrição',
    price: 22,
    active: true,
    categoryId: 'ca02',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p023',
    name: 'Petisco 3',
    description: 'Descrição',
    price: 23,
    active: true,
    categoryId: 'ca03',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p024',
    name: 'Snack 3',
    description: 'Descrição',
    price: 24,
    active: true,
    categoryId: 'ca04',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p025',
    name: 'Sobremesa 3',
    description: 'Descrição',
    price: 25,
    active: true,
    categoryId: 'ca05',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p026',
    name: 'Refrigerante 3',
    description: 'Descrição',
    price: 26,
    active: true,
    categoryId: 'ca06',
    additionals: [],
    requiredOption: [],
    imageUrl: './dist/assets/images/refri.png',
  },
  {
    id: 'p027',
    name: 'Suco 3',
    description: 'Descrição',
    price: 27,
    active: true,
    categoryId: 'ca07',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p028',
    name: 'Cerveja 3',
    description: 'Descrição',
    price: 28,
    active: true,
    categoryId: 'ca08',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p029',
    name: 'Bebida 3',
    description: 'Descrição',
    price: 29,
    active: true,
    categoryId: 'ca09',
    additionals: [],
    requiredOption: [],
  },
  {
    id: 'p030',
    name: 'Drink 3',
    description: 'Descrição',
    price: 30,
    active: true,
    categoryId: 'ca10',
    additionals: [],
    requiredOption: [],
  },
];
