import { ProductType } from '../types/ProductType';

export const productsDB: ProductType[] = [
  { id: 'p001', name: 'Entrada 1', description: 'Descrição', price: 1, active: true, category: 'Entradas' },
  { id: 'p002', name: 'Prato 1', description: 'Descrição', price: 2, active: true, category: 'Pratos' },
  { id: 'p003', name: 'Petisco 1', description: 'Descrição', price: 3, active: true, category: 'Petiscos' },
  { id: 'p004', name: 'Snack 1', description: 'Descrição', price: 4, active: true, category: 'Snacks' },
  { id: 'p005', name: 'Sobremesa 1', description: 'Descrição', price: 5, active: true, category: 'Sobremesas' },
  { id: 'p006', name: 'Refrigerante 1', description: 'Descrição', price: 6, active: true, category: 'Refrigerantes' },
  { id: 'p007', name: 'Suco 1', description: 'Descrição', price: 7, active: true, category: 'Sucos' },
  { id: 'p008', name: 'Cerveja 1', description: 'Descrição', price: 8, active: true, category: 'Cervejas' },
  { id: 'p009', name: 'Bebida 1', description: 'Descrição', price: 9, active: true, category: 'Bebidas' },
  { id: 'p010', name: 'Drink 1', description: 'Descrição', price: 10, active: true, category: 'Drinks' },
  { id: 'p011', name: 'Entrada 2', description: 'Descrição', price: 11, active: true, category: 'Entradas' },
  { id: 'p012', name: 'Prato 2', description: 'Descrição', price: 12, active: true, category: 'Pratos' },
  { id: 'p013', name: 'Petisco 2', description: 'Descrição', price: 13, active: true, category: 'Petiscos' },
  { id: 'p014', name: 'Snack 2', description: 'Descrição', price: 14, active: true, category: 'Snacks' },
  { id: 'p015', name: 'Sobremesa 2', description: 'Descrição', price: 15, active: true, category: 'Sobremesas' },
  { id: 'p016', name: 'Refrigerante 2', description: 'Descrição', price: 16, active: true, category: 'Refrigerantes' },
  { id: 'p017', name: 'Suco 2', description: 'Descrição', price: 17, active: true, category: 'Sucos' },
  { id: 'p018', name: 'Cerveja 2', description: 'Descrição', price: 18, active: true, category: 'Cervejas' },
  { id: 'p019', name: 'Bebida 2', description: 'Descrição', price: 19, active: true, category: 'Bebidas' },
  { id: 'p020', name: 'Drink 2', description: 'Descrição', price: 20, active: true, category: 'Drinks' },
  { id: 'p021', name: 'Entrada 3', description: 'Descrição', price: 21, active: true, category: 'Entradas' },
  { id: 'p022', name: 'Prato 3', description: 'Descrição', price: 22, active: true, category: 'Pratos' },
  { id: 'p023', name: 'Petisco 3', description: 'Descrição', price: 23, active: true, category: 'Petiscos' },
  { id: 'p024', name: 'Snack 3', description: 'Descrição', price: 24, active: true, category: 'Snacks' },
  { id: 'p025', name: 'Sobremesa 3', description: 'Descrição', price: 25, active: true, category: 'Sobremesas' },
  { id: 'p026', name: 'Refrigerante 3', description: 'Descrição', price: 26, active: true, category: 'Refrigerantes' },
  { id: 'p027', name: 'Suco 3', description: 'Descrição', price: 27, active: true, category: 'Sucos' },
  { id: 'p028', name: 'Cerveja 3', description: 'Descrição', price: 28, active: true, category: 'Cervejas' },
  { id: 'p029', name: 'Bebida 3', description: 'Descrição', price: 29, active: true, category: 'Bebidas' },
  { id: 'p030', name: 'Drink 3', description: 'Descrição', price: 30, active: true, category: 'Drinks' },
];
